env: local
http_server:
  host: localhost
  port: 8082
  timeout: 4s
  idle_timeout: 60s
postgres:
  host: postgres
  port: 5432
  user: postgres
  password: barghest
  db: transactions
rmq:
  url: amqp://guest:guest@rabbitmq:5672/
