env: local
http_server:
  host: localhost
  port: 8081
  timeout: 4s
  idle_timeout: 60s
postgres:
  host: postgres
  port: 5432
  user: barghest
  password: barghest
  db: users
rmq:
  url: amqp://guest:guest@rabbitmq:5672/
